/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksWorkIdRouteImport } from './routes/works.$workId'
import { Route as WorksWorkIdIndexRouteImport } from './routes/works.$workId.index'
import { Route as WorksWorkIdArcsRouteImport } from './routes/works.$workId.arcs'
import { Route as WorksWorkIdBibleRouteImport } from './routes/works.$workId.bible'
import { Route as WorksWorkIdChaptersRouteImport } from './routes/works.$workId.chapters'
import { Route as WorksWorkIdPartnerRouteImport } from './routes/works.$workId.partner'
import { Route as WorksWorkIdChaptersIndexRouteImport } from './routes/works.$workId.chapters.index'
import { Route as WorksWorkIdChaptersChapterIdRouteImport } from './routes/works.$workId.chapters.$chapterId'
import { Route as WorksWorkIdScenesSceneIdRouteImport } from './routes/works.$workId.scenes.$sceneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksWorkIdIndexRoute = WorksWorkIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdArcsRoute = WorksWorkIdArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdBibleRoute = WorksWorkIdBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdChaptersRoute = WorksWorkIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdPartnerRoute = WorksWorkIdPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => WorksWorkIdRoute,
} as any)
const WorksWorkIdChaptersIndexRoute =
  WorksWorkIdChaptersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorksWorkIdChaptersRoute,
  } as any)
const WorksWorkIdChaptersChapterIdRoute =
  WorksWorkIdChaptersChapterIdRouteImport.update({
    id: '/$chapterId',
    path: '/$chapterId',
    getParentRoute: () => WorksWorkIdChaptersRoute,
  } as any)
const WorksWorkIdScenesSceneIdRoute =
  WorksWorkIdScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => WorksWorkIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/works/$workId': typeof WorksWorkIdRouteWithChildren
  '/works/$workId/arcs': typeof WorksWorkIdArcsRoute
  '/works/$workId/bible': typeof WorksWorkIdBibleRoute
  '/works/$workId/chapters': typeof WorksWorkIdChaptersRouteWithChildren
  '/works/$workId/partner': typeof WorksWorkIdPartnerRoute
  '/works/$workId/': typeof WorksWorkIdIndexRoute
  '/works/$workId/chapters/$chapterId': typeof WorksWorkIdChaptersChapterIdRoute
  '/works/$workId/scenes/$sceneId': typeof WorksWorkIdScenesSceneIdRoute
  '/works/$workId/chapters/': typeof WorksWorkIdChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/works/$workId/arcs': typeof WorksWorkIdArcsRoute
  '/works/$workId/bible': typeof WorksWorkIdBibleRoute
  '/works/$workId/partner': typeof WorksWorkIdPartnerRoute
  '/works/$workId': typeof WorksWorkIdIndexRoute
  '/works/$workId/chapters/$chapterId': typeof WorksWorkIdChaptersChapterIdRoute
  '/works/$workId/scenes/$sceneId': typeof WorksWorkIdScenesSceneIdRoute
  '/works/$workId/chapters': typeof WorksWorkIdChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/works/$workId': typeof WorksWorkIdRouteWithChildren
  '/works/$workId/arcs': typeof WorksWorkIdArcsRoute
  '/works/$workId/bible': typeof WorksWorkIdBibleRoute
  '/works/$workId/chapters': typeof WorksWorkIdChaptersRouteWithChildren
  '/works/$workId/partner': typeof WorksWorkIdPartnerRoute
  '/works/$workId/': typeof WorksWorkIdIndexRoute
  '/works/$workId/chapters/$chapterId': typeof WorksWorkIdChaptersChapterIdRoute
  '/works/$workId/scenes/$sceneId': typeof WorksWorkIdScenesSceneIdRoute
  '/works/$workId/chapters/': typeof WorksWorkIdChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/works/$workId'
    | '/works/$workId/arcs'
    | '/works/$workId/bible'
    | '/works/$workId/chapters'
    | '/works/$workId/partner'
    | '/works/$workId/'
    | '/works/$workId/chapters/$chapterId'
    | '/works/$workId/scenes/$sceneId'
    | '/works/$workId/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/works/$workId/arcs'
    | '/works/$workId/bible'
    | '/works/$workId/partner'
    | '/works/$workId'
    | '/works/$workId/chapters/$chapterId'
    | '/works/$workId/scenes/$sceneId'
    | '/works/$workId/chapters'
  id:
    | '__root__'
    | '/'
    | '/works/$workId'
    | '/works/$workId/arcs'
    | '/works/$workId/bible'
    | '/works/$workId/chapters'
    | '/works/$workId/partner'
    | '/works/$workId/'
    | '/works/$workId/chapters/$chapterId'
    | '/works/$workId/scenes/$sceneId'
    | '/works/$workId/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorksWorkIdRoute: typeof WorksWorkIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$workId/': {
      id: '/works/$workId/'
      path: '/'
      fullPath: '/works/$workId/'
      preLoaderRoute: typeof WorksWorkIdIndexRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/arcs': {
      id: '/works/$workId/arcs'
      path: '/arcs'
      fullPath: '/works/$workId/arcs'
      preLoaderRoute: typeof WorksWorkIdArcsRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/bible': {
      id: '/works/$workId/bible'
      path: '/bible'
      fullPath: '/works/$workId/bible'
      preLoaderRoute: typeof WorksWorkIdBibleRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/chapters': {
      id: '/works/$workId/chapters'
      path: '/chapters'
      fullPath: '/works/$workId/chapters'
      preLoaderRoute: typeof WorksWorkIdChaptersRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/partner': {
      id: '/works/$workId/partner'
      path: '/partner'
      fullPath: '/works/$workId/partner'
      preLoaderRoute: typeof WorksWorkIdPartnerRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
    '/works/$workId/chapters/': {
      id: '/works/$workId/chapters/'
      path: '/'
      fullPath: '/works/$workId/chapters/'
      preLoaderRoute: typeof WorksWorkIdChaptersIndexRouteImport
      parentRoute: typeof WorksWorkIdChaptersRoute
    }
    '/works/$workId/chapters/$chapterId': {
      id: '/works/$workId/chapters/$chapterId'
      path: '/$chapterId'
      fullPath: '/works/$workId/chapters/$chapterId'
      preLoaderRoute: typeof WorksWorkIdChaptersChapterIdRouteImport
      parentRoute: typeof WorksWorkIdChaptersRoute
    }
    '/works/$workId/scenes/$sceneId': {
      id: '/works/$workId/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/works/$workId/scenes/$sceneId'
      preLoaderRoute: typeof WorksWorkIdScenesSceneIdRouteImport
      parentRoute: typeof WorksWorkIdRoute
    }
  }
}

interface WorksWorkIdChaptersRouteChildren {
  WorksWorkIdChaptersChapterIdRoute: typeof WorksWorkIdChaptersChapterIdRoute
  WorksWorkIdChaptersIndexRoute: typeof WorksWorkIdChaptersIndexRoute
}

const WorksWorkIdChaptersRouteChildren: WorksWorkIdChaptersRouteChildren = {
  WorksWorkIdChaptersChapterIdRoute: WorksWorkIdChaptersChapterIdRoute,
  WorksWorkIdChaptersIndexRoute: WorksWorkIdChaptersIndexRoute,
}

const WorksWorkIdChaptersRouteWithChildren =
  WorksWorkIdChaptersRoute._addFileChildren(WorksWorkIdChaptersRouteChildren)

interface WorksWorkIdRouteChildren {
  WorksWorkIdArcsRoute: typeof WorksWorkIdArcsRoute
  WorksWorkIdBibleRoute: typeof WorksWorkIdBibleRoute
  WorksWorkIdChaptersRoute: typeof WorksWorkIdChaptersRouteWithChildren
  WorksWorkIdPartnerRoute: typeof WorksWorkIdPartnerRoute
  WorksWorkIdIndexRoute: typeof WorksWorkIdIndexRoute
  WorksWorkIdScenesSceneIdRoute: typeof WorksWorkIdScenesSceneIdRoute
}

const WorksWorkIdRouteChildren: WorksWorkIdRouteChildren = {
  WorksWorkIdArcsRoute: WorksWorkIdArcsRoute,
  WorksWorkIdBibleRoute: WorksWorkIdBibleRoute,
  WorksWorkIdChaptersRoute: WorksWorkIdChaptersRouteWithChildren,
  WorksWorkIdPartnerRoute: WorksWorkIdPartnerRoute,
  WorksWorkIdIndexRoute: WorksWorkIdIndexRoute,
  WorksWorkIdScenesSceneIdRoute: WorksWorkIdScenesSceneIdRoute,
}

const WorksWorkIdRouteWithChildren = WorksWorkIdRoute._addFileChildren(
  WorksWorkIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorksWorkIdRoute: WorksWorkIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
